# Generated by Django 6.0.3 on 2026-03-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_watchlist_avg_rating_alter_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
